import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="container mx-auto mt-4">
      <Head>
        <title>Online Courses | Microservice Architecture</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1 className="text-base">Saya halaman utama</h1>
      </main>
    </div>
  );
}
